const fs = require('fs');

const file = 'FrontEnd/public/dictionary.json';
const dict = JSON.parse(fs.readFileSync(file, 'utf8'));

const translations = {
  // Subregions
  "Caribbean": { cs: "Karibik", de: "Karibik" },
  "Southern Asia": { cs: "Jižní Asie", de: "Südasien" },
  "Southern Europe": { cs: "Jižní Evropa", de: "Südeuropa" },
  "Polynesia": { cs: "Polynésie", de: "Polynesien" },
  "Australia and New Zealand": { cs: "Austrálie a Nový Zéland", de: "Australien und Neuseeland" },
  "Central America": { cs: "Střední Amerika", de: "Zentralamerika" },
  "Melanesia": { cs: "Melanésie", de: "Melanesien" },
  "Eastern Europe": { cs: "Východní Evropa", de: "Osteuropa" },
  "Eastern Africa": { cs: "Východní Afrika", de: "Ostafrika" },
  "South-Eastern Asia": { cs: "Jihovýchodní Asie", de: "Südostasien" },
  "Western Africa": { cs: "Západní Afrika", de: "Westafrika" },
  "Western Asia": { cs: "Západní Asie", de: "Vorderasien" },
  "South America": { cs: "Jižní Amerika", de: "Südamerika" },
  "Eastern Asia": { cs: "Východní Asie", de: "Ostasien" },
  "Northern Europe": { cs: "Severní Evropa", de: "Nordeuropa" },
  "Northern Africa": { cs: "Severní Afrika", de: "Nordafrika" },
  "Southern Africa": { cs: "Jižní Afrika", de: "Südliches Afrika" },
  "North America": { cs: "Severní Amerika", de: "Nordamerika" },
  "Southeast Europe": { cs: "Jihovýchodní Evropa", de: "Südosteuropa" },
  "Western Europe": { cs: "Západní Evropa", de: "Westeuropa" },
  "Central Asia": { cs: "Střední Asie", de: "Zentralasien" },
  "Middle Africa": { cs: "Střední Afrika", de: "Zentralafrika" },
  "Central Europe": { cs: "Střední Evropa", de: "Mitteleuropa" },
  "Micronesia": { cs: "Mikronésie", de: "Mikronesien" },

  // Languages
  "Dzongkha": { cs: "Dzongkä", de: "Dzongkha" },
  "Italian": { cs: "Italština", de: "Italienisch" },
  "Catalan": { cs: "Katalánština", de: "Katalanisch" },
  "Tuvaluan": { cs: "Tuvalština", de: "Tuvaluisch" },
  "Belizean Creole": { cs: "Belizská kreolština", de: "Belize-Kreolisch" },
  "Spanish": { cs: "Španělština", de: "Spanisch" },
  "Bislama": { cs: "Bislama", de: "Bislama" },
  "French": { cs: "Francouzština", de: "Französisch" },
  "Belarusian": { cs: "Běloruština", de: "Weißrussisch" },
  "Russian": { cs: "Ruština", de: "Russisch" },
  "Mauritian Creole": { cs: "Mauricijská kreolština", de: "Morisyen" },
  "Lao": { cs: "Laoština", de: "Laotisch" },
  "Turkish": { cs: "Turečtina", de: "Türkisch" },
  "Aymara": { cs: "Aymarština", de: "Aymara" },
  "Guaraní": { cs: "Guaraní", de: "Guaraní" },
  "Quechua": { cs: "Kečuánština", de: "Quechua" },
  "Sinhala": { cs: "Sinhálština", de: "Singhalesisch" },
  "Tamil": { cs: "Tamilština", de: "Tamilisch" },
  "Norfuk": { cs: "Norfuk", de: "Norfuk" },
  "Chinese": { cs: "Čínština", de: "Chinesisch" },
  "Dutch": { cs: "Nizozemština", de: "Niederländisch" },
  "Papiamento": { cs: "Papiamento", de: "Papiamento" },
  "Guernésiais": { cs: "Guernésiais", de: "Guernésiais" },
  "Arabic": { cs: "Arabština", de: "Arabisch" },
  "Latin": { cs: "Latina", de: "Latein" },
  "Tswana": { cs: "Tswanština", de: "Setswana" },
  "Lithuanian": { cs: "Litevština", de: "Litauisch" },
  "Kirundi": { cs: "Kirundi", de: "Kirundi" },
  "Irish": { cs: "Irština", de: "Irisch" },
  "Finnish": { cs: "Finština", de: "Finnisch" },
  "Swedish": { cs: "Švédština", de: "Schwedisch" },
  "Bengali": { cs: "Bengálština", de: "Bengalisch" },
  "Danish": { cs: "Dánština", de: "Dänisch" },
  "Romanian": { cs: "Rumunština", de: "Rumänisch" },
  "Bulgarian": { cs: "Bulharština", de: "Bulgarisch" },
  "Afrikaans": { cs: "Afrikánština", de: "Afrikaans" },
  "Herero": { cs: "Herero", de: "Otjiherero" },
  "Khoekhoe": { cs: "Khoekhoe", de: "Khoekhoe" },
  "Kwangali": { cs: "Kwangali", de: "RuKwangali" },
  "Lozi": { cs: "Lozi", de: "Silozi" },
  "Ndonga": { cs: "Ndonga", de: "Oshindonga" },
  "Norwegian": { cs: "Norština", de: "Norwegisch" },
  "Luxembourgish": { cs: "Lucemburština", de: "Luxemburgisch" },
  "Japanese": { cs: "Japonština", de: "Japanisch" },
  "Albanian": { cs: "Albánština", de: "Albanisch" },
  "Samoan": { cs: "Samojština", de: "Samoanisch" },
  "Tokelauan": { cs: "Tokelauština", de: "Tokelauisch" },
  "Tongan": { cs: "Tongánština", de: "Tongaisch" },
  "Turkmen": { cs: "Turkmenština", de: "Turkmenisch" },
  "Sango": { cs: "Sangoština", de: "Sango" },
  "Latvian": { cs: "Lotyština", de: "Lettisch" },
  "Niuean": { cs: "Niueština", de: "Niueanisch" },
  "Serbian": { cs: "Srbština", de: "Serbisch" },
  "Cook Islands Māori": { cs: "Maorština Cookových ostrovů", de: "Cookinseln-Māori" },
  "Malagasy": { cs: "Malgaština", de: "Madagassisch" },
  "Montenegrin": { cs: "Černohorština", de: "Montenegrinisch" },
  "Korean": { cs: "Korejština", de: "Koreanisch" },
  "Amharic": { cs: "Amharština", de: "Amharisch" },
  "Mongolian": { cs: "Mongolština", de: "Mongolisch" },
  "Slovak": { cs: "Slovenština", de: "Slowakisch" },
  "Norwegian Nynorsk": { cs: "Nynorsk", de: "Nynorsk" },
  "Norwegian Bokmål": { cs: "Bokmål", de: "Bokmål" },
  "Sami": { cs: "Sámština", de: "Samisch" },
  "Hebrew": { cs: "Hebrejština", de: "Hebräisch" },
  "Māori": { cs: "Maorština", de: "Māori" },
  "New Zealand Sign Language": { cs: "Novozélandský znakový jazyk", de: "Neuseeländische Gebärdensprache" },
  "Greenlandic": { cs: "Grónština", de: "Grönländisch" },
  "Kyrgyz": { cs: "Kyrgyzština", de: "Kirgisisch" },
  "Faroese": { cs: "Faerština", de: "Färöisch" },
  "Palauan": { cs: "Palauština", de: "Palauisch" },
  "Maltese": { cs: "Maltština", de: "Maltesisch" },
  "Portuguese": { cs: "Portugalština", de: "Portugiesisch" },
  "Tetum": { cs: "Tetumština", de: "Tetum" },
  "Croatian": { cs: "Chorvatština", de: "Kroatisch" },
  "Hiri Motu": { cs: "Hiri Motu", de: "Hiri Motu" },
  "Tok Pisin": { cs: "Tok Pisin", de: "Tok Pisin" },
  "Somali": { cs: "Somálština", de: "Somali" },
  "Haitian Creole": { cs: "Haitská kreolština", de: "Haitianisch" },
  "Carolinian": { cs: "Karolinština", de: "Karolinisch" },
  "Chamorro": { cs: "Čamorština", de: "Chamorro" },
  "Chewa": { cs: "Čičeva", de: "Chichewa" },
  "Uzbek": { cs: "Uzbečtina", de: "Usbekisch" },
  "Persian (Farsi)": { cs: "Perština", de: "Persisch" },
  "Kazakh": { cs: "Kazaština", de: "Kasachisch" },
  "Icelandic": { cs: "Islandština", de: "Isländisch" },
  "Slovene": { cs: "Slovinština", de: "Slowenisch" },
  "Azerbaijani": { cs: "Ázerbájdžánština", de: "Aserbaidschanisch" },
  "Swahili": { cs: "Svahilština", de: "Swahili" },
  "Burmese": { cs: "Barmština", de: "Birmanisch" },
  "Polish": { cs: "Polština", de: "Polnisch" },
  "Kikongo": { cs: "Kikongo", de: "Kikongo" },
  "Lingala": { cs: "Lingalština", de: "Lingála" },
  "Tshiluba": { cs: "Čilubština", de: "Tschiluba" },
  "Tigrinya": { cs: "Tigrinijština", de: "Tigrinya" },
  "Gilbertese": { cs: "Kiribatština", de: "Kiribatisch" },
  "Marshallese": { cs: "Marshallština", de: "Marshallisch" },
  "Chibarwe": { cs: "Chibarwe", de: "Chibarwe" },
  "Kalanga": { cs: "Kalanga", de: "Kalanga" },
  "Khoisan": { cs: "Khoisanština", de: "Khoisansprachen" },
  "Ndau": { cs: "Ndau", de: "Ndau" },
  "Northern Ndebele": { cs: "Severní Ndebele", de: "Nord-Ndebele" },
  "Shona": { cs: "Šonština", de: "Shona" },
  "Sotho": { cs: "Sothština", de: "Sesotho" },
  "Tonga": { cs: "Tongština", de: "Tonga" },
  "Tsonga": { cs: "Tsonga", de: "Xitsonga" },
  "Venda": { cs: "Vendština", de: "Tshivenda" },
  "Xhosa": { cs: "Xhoština", de: "isiXhosa" },
  "Zimbabwean Sign Language": { cs: "Zimbabwský znakový jazyk", de: "Simbabwische Gebärdensprache" },
  "Comorian": { cs: "Komorština", de: "Komorisch" },
  "Malay": { cs: "Malajština", de: "Malaiisch" },
  "Manx": { cs: "Manština", de: "Manx" },
  "Dari": { cs: "Darí", de: "Dari" },
  "Pashto": { cs: "Paštština", de: "Paschtu" },
  "Greek": { cs: "Řečtina", de: "Griechisch" },
  "Vietnamese": { cs: "Vietnamština", de: "Vietnamesisch" },
  "Aramaic": { cs: "Aramejština", de: "Aramäisch" },
  "Sorani": { cs: "Sorání", de: "Sorani" },
  "Urdu": { cs: "Urdština", de: "Urdu" },
  "Maldivian": { cs: "Maledivština", de: "Maledivisch" },
  "Berber": { cs: "Berberština", de: "Berberisch" },
  "Bosnian": { cs: "Bosenština", de: "Bosnisch" },
  "Jèrriais": { cs: "Jèrriais", de: "Jèrriais" },
  "Macedonian": { cs: "Makedonština", de: "Mazedonisch" },
  "Estonian": { cs: "Estonština", de: "Estnisch" },
  "Swiss German": { cs: "Švýcarská němčina", de: "Schweizerdeutsch" },
  "Romansh": { cs: "Rétorománština", de: "Rätoromanisch" },
  "Tajik": { cs: "Tádžičtina", de: "Tadschikisch" },
  "Southern Ndebele": { cs: "Jižní Ndebele", de: "Süd-Ndebele" },
  "Northern Sotho": { cs: "Severní Sotho", de: "Nord-Sotho" },
  "Southern Sotho": { cs: "Jižní Sotho", de: "Süd-Sotho" },
  "Swazi": { cs: "Svazijština", de: "Siswati" },
  "Zulu": { cs: "Zuluština", de: "isiZulu" },
  "Armenian": { cs: "Arménština", de: "Armenisch" },
  "Georgian": { cs: "Gruzínština", de: "Georgisch" },
  "Ukrainian": { cs: "Ukrajinština", de: "Ukrainisch" },
  "Hassaniya": { cs: "Hasaníja", de: "Hassania" },
  "Kinyarwanda": { cs: "Kinyarwanda", de: "Kinyarwanda" },
  "Basque": { cs: "Baskičtina", de: "Baskisch" },
  "Galician": { cs: "Galicijština", de: "Galicisch" },
  "Thai": { cs: "Thajština", de: "Thailändisch" },
  "Upper Guinea Creole": { cs: "Guinejská kreolština", de: "Guinea-Bissauisches Kreolisch" },
  "Hindi": { cs: "Hindština", de: "Hindi" },
  "Seychellois Creole": { cs: "Seychelská kreolština", de: "Seychellenkreol" },
  "Fijian": { cs: "Fidžijština", de: "Fidschianisch" },
  "Fiji Hindi": { cs: "Fidžijská hindština", de: "Fidschi-Hindi" },
  "Jamaican Patois": { cs: "Jamajský patois", de: "Jamaika-Kreolisch" },
  "Nauru": { cs: "Naurština", de: "Nauruisch" },
  "Indonesian": { cs: "Indonéština", de: "Indonesisch" },
  "Filipino": { cs: "Filipínština", de: "Filipino" },
  "Hungarian": { cs: "Maďarština", de: "Ungarisch" },
  "Nepali": { cs: "Nepálština", de: "Nepalesisch" },
  "Khmer": { cs: "Khmerština", de: "Khmer" }
};

for (const [key, trans] of Object.entries(translations)) {
  if (!dict[key]) {
    dict[key] = { cs: trans.cs, de: trans.de };
  } else {
    dict[key].cs = trans.cs;
    dict[key].de = trans.de;
  }
}

fs.writeFileSync(file, JSON.stringify(dict, null, 2), 'utf8');
console.log('Dictionary updated with subregions and languages.');
